### PR TITLE
local file removing as an option

### PR DESCRIPTION
**Pull request by ns3777k**
no bc. i would actually change the behavior not to delete a file by default. or maybe better to leave this up to user.

### CODE REVIEW

**Comment by milesj** [comment]
Might be better to make this config a value shared between all transporters, instead of checking for existence. Could place it here:

https://github.com/milesj/transit/blob/master/src/Transit/Transporter/AbstractTransporter.php

```php
$_config = ['removeLocal' => true];
```

I believe it gets merged with the parent and child configs.

**Comment by ns3777k** [comment]
$_config is overridden in transporters so it's not possible to put it in the abstract one as a variable.
However to make it work we can add to abstract transporter:

```php
    /**
     * Default configuration.
     *
     * @type array
     */
    protected $_defaults = array(
        'removeLocal' => true
    );

    /**
     * Store configuration.
     *
     * @param array $config
     */
    public function __construct(array $config = array()) {
        $config = array_replace_recursive($this->_defaults, $config);
        parent::__construct($config);
    }
```
Thus we define default config for any transporter. What you think?

**Comment by milesj** [comment]
Maybe we can do something that merges the parent config with the child config? Somewhere around here?

https://github.com/milesj/transit/blob/master/src/Transit/Component/AbstractComponent.php#L51

**Comment by ns3777k** [comment]
Couple of ideas:
1. define $_defaultConfig in Abstract Component, override it in Abstract Transporter with removeLocal and add this to array_replace. Thus only all transporters inherit this prop.
2. override $_config in Abstract Transporter with removeLocal and rename $_config in non-abstract transporters not to override it. But the renamed prop has to be merged in constructor with the config coming from the args. It can be done in Abstract Transporter not to merge it in every non-abstract one.

**Comment by milesj** [comment]
Case 1 seems like the better option.

**Comment by ns3777k** [comment]
updated code

**Comment by milesj** [comment]
Looks good, thanks!

**Pull request merged**
